



RESOURCE_DIR = My_Space/my_projects/PHM01_Test/
SOURCE_DIR = My_Space/my_projects/PHM01_Test/

pipeline: [
            {
                "source": {
                           "name": "Chronic Disease Indicator",
;                          "type": "db",
                           "file_input_path": "${RESOURCE_DIR}PHM01_Test/input_files/",
                           "file_output_path": "${RESOURCE_DIR}PHM01_Test/output_files/",
                           "template_path": "${RESOURCE_DIR}PHM01_Test/template/"
                           "file_one": "PHM01_Report_filled_20251229_040547.xlsx"
;                          "connection": - ini connection to db
;                   queries": [
;                                    {
;                                         "name": alias for the query
;                                         "file_path": location of the query
;                                        "file mask": sql query name
;                                    }
;                                ]

                            }'
                    "target": [
;;                                {
;;                                "type": "csv or xlsx"
;;                                "file_name":  "df_chronic_condit_indic"
;;                                               ^^^ input file name
;;                                "query_name": alias asigned on name
;                                "report_name":U.S_Chronic_Disease_Indicators.csv
;                                }
                              ]
                }
              ]



