[paths]
base_dir = .

template_dir = templates
template_file = PHM01_template.xlsx

input_dir = input_files
;input_prefix = PHM01_Report_Data.xlsx

output_dir = output_files

output_prefix = PHM01_Report_filled_
output_ext = .xlsx
